pipeline:
  dockerfile:
    image: alpine
    commands:
      - sed -i -e "s/latest/${TAG}/1" Dockerfile

  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/eve/alpine
    tag: ${TAG}
    file: Dockerfile-${TAG}

  notify:
    image: no-cloud.fr/drone-xmpp
    secrets: [ xmpp_jid, xmpp_password, xmpp_to ]

matrix:
  TAG:
    - 3.1
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - latest
    - edge
